# Generated by Django 4.2.11 on 2024-04-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_customer_email_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
