# Generated by Django 4.2.11 on 2024-04-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='passw',
        ),
    ]
