# Generated by Django 4.2.11 on 2024-04-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_shippingaddress_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='_guest_email',
            new_name='_email',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='_guest_username',
            new_name='_username',
        ),
    ]
