# Generated by Django 4.2.11 on 2024-04-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='my_products',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
